version: "3"
services:
  db-container-ro:
    image: "mysql:5.7"
    container_name: db-container-ro
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    volumes:
      - ./db/data:/var/lib/mysql
      # - ./public/sql/adminbo_start.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  web-container-ro:
    build: .
    container_name: web-container-ro
    restart: always
    volumes:
      - .:/code
    ports:
      - "80:80"
